<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartelera[
    <!ELEMENT cartelera (pelicula*)>
    <!--* Indica o cero o muchos
    +Una o muchas peliculas-->
    <!ELEMENT pelicula (titulo, directores*, (anyo | fecha))>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT anyo (#PCDATA)>
    <!ELEMENT directores (director+)>
    <!ELEMENT director (nombre)>
    <!ELEMENT nombre (#PCDATA)>
]>

<cartelera>
    <pelicula>
        <titulo>Tibur√≥n</titulo>
        <directores>
            <director>
                <nombre>Steven Spierlberg</nombre>
            </director>
        </directores>
        <anyo>1975</anyo>
    </pelicula>

    <pelicula>
        <titulo>Matrix</titulo>
        <directores>
            <director>
                <nombre>Lilly Wachowski</nombre>
            </director>
            <director>
                <nombre>Lana Wachowski</nombre>
            </director>
        </directores>
        <anyo>1999</anyo>
    </pelicula>

</cartelera> 
