<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartelera[
    <!ELEMENT cartelera (pelicula*)>
    <!ELEMENT pelicula (directores)>
    <!ELEMENT directores (director+)>
    <!ELEMENT director EMPTY>

    <!ATTLIST pelicula id ID #REQUIRED>
    <!ATTLIST director id ID #REQUIRED>
    <!ATTLIST pelicula titulo CDATA #REQUIRED>
    <!ATTLIST pelicula anyo CDATA #REQUIRED>
    <!ATTLIST director nombre CDATA #REQUIRED>
]>

<cartelera>
    <pelicula id="P1" titulo="TiburÃ³n" anyo="1975">
        <directores>
            <director id="D1" nombre="Steven Spierlberg" />
        </directores>

    </pelicula>
    
    <pelicula id="P2" titulo="Matrix" anyo="1999">
        <directores>
            <director id="D2" nombre="Lilly Wachowski" />
            <director id="D3" nombre="Lana Wachowski" /> 
        </directores>
    </pelicula>

</cartelera> 
